import udemy from '../../assets/companies/udemy2.png';
import microsoft from '../../assets/companies/microsoft.png';
import devMedia from '../../assets/companies/devMedia.jpeg';

export const certifications = [
  {
    id: 0,
    type: 'frontend',
    status: true,
    category: 'Frontend + Backend',
    featuredIcon: 'bookmark',
    name: 'Desenvolvimento Web com React e Node.js',
    icon: 'bx bxl-react',
    img: udemy,
    institution: 'Udemy',
    conclusion: '2023',
    duration: null,
    tags: ['React', 'Node.js', 'Full stack'],
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 1,
    type: 'frontend',
    status: true,
    category: 'Linguagens Web',
    featuredIcon: '',
    name: 'JavaScript e TypeScript do básico ao avançado JS/TS',
    icon: "bx bxl-javascript",
    img: udemy,
    institution: 'Udemy',
    conclusion: 'Abr de 2025',
    duration: null,
    tags: ['JavaScript', 'TypeScript'],
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 2,
    type: 'backend',
    status: true,
    category: 'Desenvolvimento Backend',
    featuredIcon: '',
    name: 'Fundamentos de Python para Backend',
    icon: 'bx bxl-python',
    img: udemy,
    institution: 'Udemy',
    conclusion: '2022',
    duration: null,
    tags: ['Python', 'Backend'],
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 3,
    type: 'banco de dados',
    status: true,
    category: 'Banco de Dados',
    featuredIcon: '',
    name: 'Bancos de Dados com SQL e MySQL',
    icon: 'bx bx-data',
    img: udemy,
    institution: 'Udemy',
    conclusion: '2023',
    duration: null,
    tags: ['SQL', 'MySQL'],
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 4,
    type: 'frontend',
    status: true,
    category: 'Fundamentos Frontend',
    featuredIcon: '',
    name: 'Certificado de autoridade: HTML',
    icon: 'bx bxl-html5',
    img: devMedia,
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: null,
    tags: ['HTML5'],
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 5,
    type: 'frontend',
    status: true,
    category: 'Linguagens Web',
    featuredIcon: '',
    name: 'Certificado de autoridade: JavaScript',
    icon: "bx bxl-javascript",
    img: devMedia,
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: null,
    tags: ['JavaScript'],
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 6,
    type: 'backend',
    status: true,
    category: 'Desenvolvimento Backend',
    featuredIcon: '',
    name: 'Certificado de autoridade: Node.js',
    icon: 'bx bxl-nodejs',
    img: devMedia,
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: null,
    tags: ['Node.js'],
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 7,
    type: 'outros',
    status: true,
    category: 'Fundamentos de Programação',
    featuredIcon: '',
    name: 'Certificado de autoridade: Programação',
    icon: 'bx bx-code-alt',
    img: devMedia,
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: null,
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 8,
    type: 'frontend',
    status: true,
    category: 'Frontend',
    featuredIcon: '',
    name: 'React',
    icon: "bx bxl-react",
    img: devMedia,
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: null,
    tags: ['React'],
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 9,
    type: 'outros',
    status: true,
    category: 'Versionamento',
    featuredIcon: '',
    name: 'Como criar e modificar um projeto Git',
    icon: 'bx bxl-git',
    img: microsoft,
    institution: 'Microsoft',
    conclusion: 'Abr de 2024',
    duration: null,
    tags: ['Git'],
    link_institution: 'https://learn.microsoft.com/training/',
    mediaClassName: 'border border-outline/70',
  }
];

export const certificationFilters = [
  { key: 'all', label: 'Todos' },
  { key: 'featured', label: 'Destaques' },
  { key: 'ia', label: 'IA' },
  { key: 'backend', label: 'Backend' },
  { key: 'frontend', label: 'Frontend' },
  { key: 'banco de dados', label: 'Dados' },
  { key: 'outros', label: 'Outros' },
];

const certificationFilterAliases = {
  all: 'all',
  tudo: 'all',
  featured: 'featured',
  destaque: 'featured',
  destaques: 'featured',
  ia: 'ia',
  'inteligencia artificial': 'ia',
  'inteligência artificial': 'ia',
  backend: 'backend',
  frontend: 'frontend',
  linguagens: 'frontend',
  dados: 'banco de dados',
  'banco de dados': 'banco de dados',
  outros: 'outros',
};

export function normalizeCertificationFilter(filterValue) {
  const normalizedValue = String(filterValue ?? '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');

  return certificationFilterAliases[normalizedValue] ?? 'all';
}
