import udemy from '../../assets/companies/udemy2.png';
import cursoEmVideo from '../../assets/companies/curso-em-video.jpg';
import telos from '../../assets/companies/telos.jpeg';
import microsoft from '../../assets/companies/microsoft.png';
import estudonauta from '../../assets/companies/estudonauta.jpg';
import alura from '../../assets/companies/alura.png';

export const certifications = [

  {
    id: -4,
    type: 'linguagens',
    status: false,
    name: 'JAVA',
    icon: "bx bxl-javascript",
    img: alura,
    description: 'Aplicando Orientação à Objetos',
    institution: 'Alura',
    conclusion: '2024',
    duration: '10 horas',
    link_institution: 'https://www.alura.com.br/curso-online-java-aplicando-orientacao-objetos',
    style_icone: {borderRadius: '3px'},
  },

  {
    id: -3,
    type: 'linguagens',
    status: true,
    name: 'JAVA: primeira aplicação',
    icon: "bx bxl-javascript",
    img: alura,
    description: 'Condicionais, repetição, ecossistema, tipos de dados... ',
    institution: 'Alura',
    conclusion: '2024',
    duration: '8 horas',
    link_institution: 'https://www.alura.com.br/curso-online-java-criando-primeira-aplicacao',
    style_icone: {borderRadius: '3px'},
  },
  
  {
    id: -2,
    type: 'banco de dados',
    status: true,
    name: 'Banco de Dados e SQL',
    icon: "bx bxl-javascript",
    img: udemy,
    description: 'Business Intelligence, SQL Server, MySQL, Oracle, T-SQL e PLSQL',
    institution: 'Udemy',
    conclusion: '2024',
    duration: '58,5 horas',
    link_institution: 'https://www.udemy.com/course/bancos-de-dados-relacionais-basico-avancado/?couponCode=KEEPLEARNING',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: -1,
    type: 'backend',
    status: true,
    name: 'Node.js',
    icon: "",
    img: udemy,
    description: 'Node.js do zero a Maestria com diversos Projetos',
    institution: 'Udemy',
    conclusion: '2024',
    duration: '38 horas',
    link_institution: 'https://www.udemy.com/course/nodejs-do-zero-a-maestria-com-diversos-projetos/?couponCode=KEEPLEARNING',
    style_icone: {borderRadius: '3px'},
  },
  
  {
    id: 0,
    type: 'linguagens',
    status: true,
    name: 'Javascript',
    icon: "bx bxl-javascript",
    img: udemy,
    description: 'JavaScript e TypeScript do básico ao avançado',
    institution: 'Udemy',
    conclusion: '2024',
    duration: '93 horas',
    link_institution: 'https://www.udemy.com/course/curso-de-javascript-moderno-do-basico-ao-avancado/?couponCode=KEEPLEARNING',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 1,
    type: 'frontend',
    status: true,
    name: 'React + Next.js',
    icon: "bx bxl-react",
    img: udemy,
    description: 'React.Js e Next.Js (Intermediário e Avançado)',
    institution: 'Udemy',
    conclusion: '2024',
    duration: '146 horas',
    link_institution: 'https://www.udemy.com/course/curso-de-reactjs-nextjs-completo-do-basico-ao-avancado/?couponCode=KEEPLEARNING',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 2,
    type: 'frontend',
    status: true,
    name: 'HTML5 e CSS3',
    icon: "bx bxl-html5",
    img: cursoEmVideo,
    description: 'Do básico ao avançado',
    institution: 'Curso em vídeo',
    conclusion: '2023',
    duration: '160 horas',
    link_institution: 'https://www.cursoemvideo.com/',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 3,
    type: 'backend',
    status: true,
    name: 'Backend',
    icon: "bx bxl-nodejs",
    img: telos,
    description: 'Capacitação backend com nodejs e MongoDB',
    institution: 'Télos',
    conclusion: '2024',
    duration: 'null',
    link_institution: 'https://www.telosconecta.com/en-US',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 4,
    type: 'linguagens',
    status: true,
    name: 'Python',
    icon: "bx bxl-python",
    img: cursoEmVideo,
    description: 'Do básico ao avançado',
    institution: 'Curso em vídeo',
    conclusion: '2022',
    duration: '120 horas',
    link_institution: 'https://www.cursoemvideo.com/',
    link_credential: '',
    style_icone: {borderRadius: '3px'},
  },
  
  {
    id: 5,
    type: 'outros',
    status: true,
    name: 'git',
    icon: "bx bxl-git",
    img: microsoft,
    description: 'Introdução ao Git',
    institution: 'Microsoft Learn',
    conclusion: '2024',
    duration: 'null',
    link_institution: 'https://learn.microsoft.com/pt-br/training/browse/',
    link_credential: 'https://drive.google.com/file/d/1hKURT3dkYVdj1A6jdXkFCl_AMrobokFh/view',
    style_icone: {border: '1px solid #c7c6bf'},
  },

  {
    id: 6,
    type: 'outros',
    status: true,
    name: 'git',
    icon: "bx bxl-git",
    img: microsoft,
    description: 'Como criar e modificar um projeto Git',
    institution: 'Microsoft Learn',
    conclusion: '2024',
    duration: 'null',
    link_institution: 'https://learn.microsoft.com/pt-br/training/browse/',
    link_credential: 'https://drive.google.com/file/d/1hKw_BF0ucbKRE3nSW0l2_6UvyPsvkshb/view',
    style_icone: {border: '1px solid #c7c6bf'},
  },

  {
    id: 7,
    type: 'frontend',
    status: true,
    name: 'React',
    icon: "bx bxl-react",
    img: telos,
    description: 'Programa de capacitação da Télos',
    institution: 'Télos',
    conclusion: '2023',
    duration: 'null',
    link_institution: 'https://www.telosconecta.com/en-US',
    link_credential: '',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 8,
    type: 'outros',
    status: true,
    name: 'Git + GitHub',
    icon: "bx bxl-github",
    img: telos,
    description: 'Programa de capacitação da Télos',
    institution: 'Télos',
    conclusion: '2023',
    duration: 'null',
    link_institution: 'https://www.telosconecta.com/en-US',
    link_credential: '',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 9,
    type: 'outros',
    status: true,
    name: 'Wordpress',
    icon: "bx bxl-wordpress",
    img: estudonauta,
    description: 'Wordpress com gutenberg',
    institution: 'Estudonauta',
    conclusion: '2021',
    duration: '80 horas',
    link_institution: 'https://www.estudonauta.com/',
    link_credential: '',
    style_icone: {borderRadius: '3px'},
  },
  {
    id: 10,
    type: 'linguagens',
    status: true,
    name: 'Algoritmo + visualG',
    icon: '',
    img: cursoEmVideo,
    description: 'Algoritmos e Lógica de Programação',
    institution: 'Curso em vídeo',
    conclusion: '2020',
    duration: '40 horas',
    link_institution: 'https://www.cursoemvideo.com/',
    link_credential: '',
    style_icone: {borderRadius: '3px'},
  }
];