import udemy from '../../assets/companies/udemy2.png';
import microsoft from '../../assets/companies/microsoft.png';
import devMedia from '../../assets/companies/devMedia.jpeg';

export const certifications = [
  {
    id: 0,
    type: 'frontend',
    status: true,
    name: 'Desenvolvimento Web com React e Node.js',
    icon: 'bx bxl-react',
    img: udemy,
    description: 'Formação prática em aplicações web full stack com foco em React e Node.js.',
    institution: 'Udemy',
    conclusion: '2023',
    duration: 'Não informado',
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 1,
    type: 'linguagens',
    status: true,
    name: 'JavaScript e TypeScript do básico ao avançado JS/TS',
    icon: "bx bxl-javascript",
    img: udemy,
    description: 'Base sólida em linguagem, tipagem, lógica e aplicações práticas com JS e TS.',
    institution: 'Udemy',
    conclusion: 'Abr de 2025',
    duration: 'Não informado',
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 2,
    type: 'linguagens',
    status: true,
    name: 'Fundamentos de Python para Backend',
    icon: 'bx bxl-python',
    img: udemy,
    description: 'Base de Python aplicada ao contexto de desenvolvimento backend.',
    institution: 'Udemy',
    conclusion: '2022',
    duration: 'Não informado',
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 3,
    type: 'banco de dados',
    status: true,
    name: 'Bancos de Dados com SQL e MySQL',
    icon: 'bx bx-data',
    img: udemy,
    description: 'Modelagem, consultas e fundamentos de bancos relacionais com SQL e MySQL.',
    institution: 'Udemy',
    conclusion: '2023',
    duration: 'Não informado',
    link_institution: 'https://www.udemy.com/',
  },
  {
    id: 4,
    type: 'frontend',
    status: true,
    name: 'Certificado de autoridade: HTML',
    icon: 'bx bxl-html5',
    img: devMedia,
    description: 'Fundamentos e boas práticas de HTML para desenvolvimento web.',
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: 'Não informado',
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 5,
    type: 'linguagens',
    status: true,
    name: 'Certificado de autoridade: JavaScript',
    icon: "bx bxl-javascript",
    img: devMedia,
    description: 'Conceitos de linguagem e lógica aplicada ao desenvolvimento web.',
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: 'Não informado',
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 6,
    type: 'backend',
    status: true,
    name: 'Certificado de autoridade: Node.js',
    icon: 'bx bxl-nodejs',
    img: devMedia,
    description: 'Fundamentos de backend com Node.js e estruturação de aplicações.',
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: 'Não informado',
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 7,
    type: 'outros',
    status: true,
    name: 'Certificado de autoridade: Programação',
    icon: 'bx bx-code-alt',
    img: devMedia,
    description: 'Base geral de programação e resolução de problemas.',
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: 'Não informado',
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 8,
    type: 'frontend',
    status: true,
    name: 'React',
    icon: "bx bxl-react",
    img: devMedia,
    description: 'Construção de interfaces e componentes com React.',
    institution: 'DevMedia',
    conclusion: 'Mai de 2024',
    duration: 'Não informado',
    link_institution: 'https://www.devmedia.com.br/',
  },
  {
    id: 9,
    type: 'outros',
    status: true,
    name: 'Como criar e modificar um projeto Git',
    icon: 'bx bxl-git',
    img: microsoft,
    description: 'Versionamento e fluxo de trabalho com Git.',
    institution: 'Microsoft',
    conclusion: 'Abr de 2024',
    duration: 'Não informado',
    link_institution: 'https://learn.microsoft.com/training/',
    mediaClassName: 'border border-outline/70',
  }
];

export const certificationFilters = [
  { key: 'all', label: 'Tudo' },
  { key: 'backend', label: 'Backend' },
  { key: 'frontend', label: 'Frontend' },
  { key: 'linguagens', label: 'Linguagens' },
  { key: 'banco de dados', label: 'Banco de dados' },
  { key: 'softskills', label: 'Soft Skills' },
  { key: 'outros', label: 'Outros' },
];

const certificationFilterAliases = {
  all: 'all',
  tudo: 'all',
  backend: 'backend',
  frontend: 'frontend',
  linguagens: 'linguagens',
  'banco de dados': 'banco de dados',
  softskills: 'softskills',
  'soft skills': 'softskills',
  outros: 'outros',
};

export function normalizeCertificationFilter(filterValue) {
  const normalizedValue = String(filterValue ?? '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');

  return certificationFilterAliases[normalizedValue] ?? 'all';
}
